// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.23.0";

// src/lib/mcp/tools/list-portfolio-companies.ts
import { createClient } from "npm:@supabase/supabase-js@^2.95.2";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.23.0";
function supabaseForUser(ctx) {
  return createClient(globalThis.Deno.env.get("SUPABASE_URL"), globalThis.Deno.env.get("SUPABASE_PUBLISHABLE_KEY"), {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_portfolio_companies_default = defineTool({
  name: "list_portfolio_companies",
  title: "List portfolio companies",
  description: "List Rhino Ventures portfolio companies approved for portal access, including their primary email domain and logo key.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("approved_domains").select("company_name, domain, logo_key").order("company_name");
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { companies: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-events.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.95.2";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z } from "npm:zod@^3.25.76";
function supabaseForUser2(ctx) {
  return createClient2(globalThis.Deno.env.get("SUPABASE_URL"), globalThis.Deno.env.get("SUPABASE_PUBLISHABLE_KEY"), {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_events_default = defineTool2({
  name: "list_events",
  title: "List portal events",
  description: "List Rhino Ventures portal events (upcoming and past). Returns title, date, description, and any linked recording URL.",
  inputSchema: {
    limit: z.number().int().min(1).max(100).optional().describe("Maximum number of events to return. Defaults to 25.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser2(ctx);
    const { data, error } = await supabase.from("events").select("*").order("event_date", { ascending: false }).limit(limit ?? 25);
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { events: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-resources.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.95.2";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z2 } from "npm:zod@^3.25.76";
function supabaseForUser3(ctx) {
  return createClient3(globalThis.Deno.env.get("SUPABASE_URL"), globalThis.Deno.env.get("SUPABASE_PUBLISHABLE_KEY"), {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_resources_default = defineTool3({
  name: "list_resources",
  title: "List portal resources",
  description: "List resources available in the Rhino portal (playbooks, templates, guides). Optionally filter by category.",
  inputSchema: {
    category: z2.string().optional().describe("Optional category filter, e.g. 'Fundraising', 'Hiring'.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ category }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser3(ctx);
    let q = supabase.from("resources").select("id, title, description, url, category, approval_required, created_at").order("category").order("title");
    if (category) q = q.eq("category", category);
    const { data, error } = await q;
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { resources: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-partnerships.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.95.2";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z3 } from "npm:zod@^3.25.76";
function supabaseForUser4(ctx) {
  return createClient4(globalThis.Deno.env.get("SUPABASE_URL"), globalThis.Deno.env.get("SUPABASE_PUBLISHABLE_KEY"), {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_partnerships_default = defineTool4({
  name: "list_partnerships",
  title: "List portfolio partnerships",
  description: "List Rhino Ventures partnership offers available to portfolio companies. Includes vendor name, category, and offer summary.",
  inputSchema: {
    category: z3.string().optional().describe("Optional category filter, e.g. 'Sales & Marketing'.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ category }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser4(ctx);
    let q = supabase.from("partnerships").select("*").order("name");
    if (category) q = q.eq("category", category);
    const { data, error } = await q;
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { partnerships: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/whoami.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.23.0";
var whoami_default = defineTool5({
  name: "whoami",
  title: "Who am I",
  description: "Return the identity of the signed-in Rhino portal user (email and user id).",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const identity = {
      userId: ctx.getUserId(),
      email: ctx.getUserEmail(),
      clientId: ctx.getClientId()
    };
    return {
      content: [{ type: "text", text: JSON.stringify(identity, null, 2) }],
      structuredContent: identity
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "dqhkyfvtrgcbtbymglyk";
var mcp_default = defineMcp({
  name: "rhino-portal-mcp",
  title: "Rhino Ventures Partner Portal",
  version: "0.1.0",
  instructions: "Tools for the Rhino Ventures Partner Portal. Signed-in portfolio company users and Rhino admins can list portfolio companies, events, resources, and partnership offers. All reads run as the signed-in user under portal access rules.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [whoami_default, list_portfolio_companies_default, list_events_default, list_resources_default, list_partnerships_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.23.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
